### ISSUE TITLE
Normal sample as controls

### ISSUE THREAD

**Issue by yeswzc** [mwsill/mnp_training#2]
Hi,
Thank you for offering this great Github resource.
 I tried to repeat the analysis in the nature paper. But I met some problem, I hope you could help, please.
The pipeline do not work, as:
1. for CNV analysis, you mentioned that 'Two sets of 50 control samples displaying a balanced copy-number profile from both male and female donors were used for normalization.' The 50 samples' data seems not in the GSE accession. I did not see samples labeled as 'normal'. Could you give out the data? And how to integrated them?

2. for CNV analysis, did you use the batch effect removed 'Mset' or the 'MNPpreprocessIllumina processed Mset' ? 

3. I saw four batch by:
> levels(factor(anno$`material:ch1`))
[1] "DNA_FFPE" "DNA_KRYO" "FFPE"     "Frozen"

Here, what is DNA_FFPE and what is DNA_KRYO? They seemed not explained in the paper, are they also FFPE? If not, how to remove the batch effect?

Thank you very much!

**Comment by mwsill** [comment]
Hi,

1. and 2.  I was not able to gather all the raw idat files of the 100 normal control samples, because many of them were taken from a minif RGset available in this Bioconductor-package

https://bioconductor.org/packages/3.4/data/experiment/html/CopyNumber450kData.html

We do not own the idat files and the CopyNumber450kData package is outdated so that you need to downgrade your minfi package to access the data. 

To make things more simple, I have uploaded our conumee reference objects with the 50 female and 50 male samples as well as the annotation object that we use. Together with these you should be able to follow the steps in the newly uploaded R script cnv_analysis.R to generate the same CNV plots that we presented in the manuscript.

To download the reference objects you need Git large file storage installed:

https://git-lfs.github.com/

and then simply clone the repo:

git clone https://github.com/mwsill/mnp_training.git

3. FFPE == DNA_FFPE  and DNA_KRYO == Frozen

Best,

Martin
